
export const OPEN_ORDER_MODAL: 'OPEN_ORDER_MODAL' = 'OPEN_ORDER_MODAL';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';

export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM';
export const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM';

export const GET_API_ITEMS_SUCCESS: 'GET_API_ITEMS_SUCCES' = 'GET_API_ITEMS_SUCCES';

export const GET_SERV_ORDER_REQUEST: 'GET_SERV_ORDER_REQUEST' = 'GET_SERV_ORDER_REQUEST';
export const GET_SERV_ORDER_SUCCESS: 'GET_SERV_ORDER_SUCCESS' = 'GET_SERV_ORDER_SUCCESS';
export const GET_SERV_ORDER_FAILED: 'GET_SERV_ORDER_FAILED' = 'GET_SERV_ORDER_FAILED';

export const CHANGE_ITEM: 'CHANGE_ITEM' = 'CHANGE_ITEM';


