export const USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS' = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST' = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_FAILED: 'USER_REGISTER_FAILED' = 'USER_REGISTER_FAILED';

export const USER_FORGOT_SUCCESS: 'USER_FORGOT_SUCCESS' = 'USER_FORGOT_SUCCESS';
export const USER_FORGOT_REQUEST: 'USER_FORGOT_REQUEST' = 'USER_FORGOT_REQUEST';
export const USER_FORGOT_FAILED: 'USER_FORGOT_FAILED' = 'USER_FORGOT_FAILED';

export const USER_RESETPASSWORD_SUCCESS: "USER_RESETPASSWORD_SUCCESS" = "USER_RESETPASSWORD_SUCCESS";
export const USER_RESETPASSWORD_REQUEST: 'USER_RESETPASSWORD_REQUEST' = 'USER_RESETPASSWORD_REQUEST';
export const USER_RESETPASSWORD_FAILED: 'USER_RESETPASSWORD_FAILED' = 'USER_RESETPASSWORD_FAILED';

export const USER_AUTHORIZATION_SUCCESS: 'USER_AUTHORIZATION_SUCCESS' = 'USER_AUTHORIZATION_SUCCESS';
export const USER_AUTHORIZATION_REQUEST: 'USER_AUTHORIZATION_REQUEST' = 'USER_AUTHORIZATION_REQUEST';
export const USER_AUTHORIZATION_FAILED: 'USER_AUTHORIZATION_FAILED' = 'USER_AUTHORIZATION_FAILED';


export const USER_LOGOUT: 'USER_LOGOUT' = 'USER_LOGOUT';

export const UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE' = 'UPDATE_USER_PROFILE';